# Generated by Django 4.1 on 2023-05-04 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialq', '0002_alter_specialsubmit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsubmit',
            name='time',
            field=models.TimeField(default=datetime.time(9, 19, 48, 63246), verbose_name='提交时间'),
        ),
    ]
