# Generated by Django 4.1 on 2023-05-04 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialq', '0004_alter_specialsubmit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialsubmit',
            name='time',
        ),
        migrations.AddField(
            model_name='specialsubmit',
            name='Time',
            field=models.TimeField(default=datetime.time(12, 18, 42, 352230), verbose_name='提交时间'),
        ),
    ]
