# Generated by Django 4.1 on 2023-05-04 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialq', '0006_alter_specialsubmit_agent_alter_specialsubmit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsubmit',
            name='Time',
            field=models.TimeField(default=datetime.time(14, 50, 16, 327835), verbose_name='提交时间'),
        ),
        migrations.AddConstraint(
            model_name='specialsubmit',
            constraint=models.UniqueConstraint(fields=('WjId', 'Agent'), name='unique_WjId_Agent'),
        ),
    ]
