# Generated by Django 4.1.7 on 2023-05-09 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialq', '0007_alter_specialsubmit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsubmit',
            name='Data',
            field=models.DateField(default=datetime.date(2023, 5, 9), verbose_name='提交日期'),
        ),
        migrations.AlterField(
            model_name='specialsubmit',
            name='Time',
            field=models.TimeField(default=datetime.time(9, 11, 36, 376829), verbose_name='提交时间'),
        ),
    ]
