# Generated by Django 4.1 on 2023-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Abstract', models.CharField(max_length=2000)),
                ('Title_CN', models.CharField(max_length=100)),
                ('Abstract_CN', models.CharField(max_length=2000)),
                ('Link', models.CharField(max_length=100)),
                ('Meeting', models.CharField(max_length=50)),
                ('Complete', models.BooleanField(default=False)),
                ('Locked', models.BooleanField(default=False)),
                ('Select1', models.BooleanField(default=False)),
                ('Select2', models.BooleanField(default=False)),
            ],
        ),
    ]
