# Generated by Django 4.1 on 2023-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Abstract',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Abstract_CN',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Title_CN',
            field=models.CharField(max_length=500),
        ),
    ]
